{"Id": "63252043", "PostTypeId": "1", "AcceptedAnswerId": "63256674", "CreationDate": "2020-08-04T17:22:36.817", "Score": "2", "ViewCount": "179", "Body": "<p>I'm trying to deploy cloudformation template with the help of this URL: <a href=\"https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/\" rel=\"nofollow noreferrer\">https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/</a></p>\n<p>After sometimes it failed to create and <code>ROLLBACK_IN_PROGRESS</code> and then <code>DELETE_IN_PROGRESS</code> and finally <code>DELETE_COMPLETE</code></p>\n<p><strong>CloudWatch Logs</strong></p>\n<pre><code>.......\n{\n    &quot;message&quot;: &quot;internal server error&quot;,\n    &quot;code&quot;: &quot;InternalServerErrorException&quot;,\n    &quot;time&quot;: &quot;2020-08-04T15:37:35.622Z&quot;,\n    &quot;requestId&quot;: &quot;dfffa7cc-bba8-44ae-bec4-507a8cc822af&quot;,\n    &quot;statusCode&quot;: 500,\n    &quot;retryable&quot;: true\n}\n......\n</code></pre>\n<p><strong>Screenshots:</strong>\nCloudWatch log screenshot</p>\n<p><img src=\"https://i.stack.imgur.com/OhBTX.png\" alt=\"1\" /></p>\n<p>Creation failed event screenshot</p>\n<p><img src=\"https://i.stack.imgur.com/vQTQn.png\" alt=\"2\" /></p>\n<p>MediaPackageVod and MediaConvertTemplates are the only two logicalID which fails to create. Due to these <code>ROLLBACK_IN_PROGRESS</code> initiated.</p>\n", "OwnerUserId": "11850616", "LastActivityDate": "2020-08-05T08:09:56.010", "Title": "Video on Demand on AWS cloudformation template failed to create", "Tags": "|amazon-s3|aws-lambda|aws-cloudformation|", "AnswerCount": "1", "CommentCount": "0", "FavoriteCount": "0", "ContentLicense": "CC BY-SA 4.0", "history": [{"Id": "228099535", "PostHistoryTypeId": "2", "PostId": "63252043", "RevisionGUID": "2aeacc27-98df-4d57-8af2-603cf458201a", "CreationDate": "2020-08-04T17:22:36.817", "UserId": "11850616", "Text": "I'm trying to deploy cloudformation template with the help of this URL: https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/\r\n\r\nAfter sometimes it failed to create and `ROLLBACK_IN_PROGRESS` and then `DELETE_IN_PROGRESS` and finally `DELETE_COMPLETE`\r\n\r\n**CloudWatch Logs**\r\n\r\n    .......\r\n    {\r\n        \"message\": \"internal server error\",\r\n        \"code\": \"InternalServerErrorException\",\r\n        \"time\": \"2020-08-04T15:37:35.622Z\",\r\n        \"requestId\": \"dfffa7cc-bba8-44ae-bec4-507a8cc822af\",\r\n        \"statusCode\": 500,\r\n        \"retryable\": true\r\n    }\r\n    ......\r\n\r\n**Screenshots:**\r\nCloudWatch log screenshot\r\n\r\n![1]\r\n\r\nCreation failed event screenshot\r\n\r\n![2]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/OhBTX.png\r\n  [2]: https://i.stack.imgur.com/vQTQn.png\r\n\r\nMediaPackageVod and MediaConvertTemplates are the only two logicalID which fails to create. Due to these `ROLLBACK_IN_PROGRESS` initiated.", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "228099536", "PostHistoryTypeId": "1", "PostId": "63252043", "RevisionGUID": "2aeacc27-98df-4d57-8af2-603cf458201a", "CreationDate": "2020-08-04T17:22:36.817", "UserId": "11850616", "Text": "Video on Demand on AWS cloudformation template failed to create", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "228099537", "PostHistoryTypeId": "3", "PostId": "63252043", "RevisionGUID": "2aeacc27-98df-4d57-8af2-603cf458201a", "CreationDate": "2020-08-04T17:22:36.817", "UserId": "11850616", "Text": "|amazon-s3|aws-lambda|aws-cloudformation|", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "answers": [{"Id": "63256674", "PostTypeId": "2", "ParentId": "63252043", "CreationDate": "2020-08-05T00:10:33.897", "Score": "1", "Body": "<p>The <strong>template works</strong>. I deployed it myself on my sandbox account. Thus, I can't replicate the issue and the fault must be somewhere else.</p>\n<p><a href=\"https://i.stack.imgur.com/2Q7w5.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/2Q7w5.png\" alt=\"enter image description here\" /></a></p>\n<p>I used <code>us-east-1</code> region with all values of the template set to their default. Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources?</p>\n<p>If this helps, in your case the lambda function associated with the  following custom resource fails:</p>\n<pre><code>  MediaPackageVod:\n    Type: Custom::LoadLambda\n    Properties:\n      ServiceToken: !GetAtt CustomResource.Arn\n      Resource: MediaPackageVod\n      StackName: !Ref AWS::StackName\n      GroupId: !Sub &quot;${AWS::StackName}-packaging-group&quot;\n      PackagingConfigurations: &quot;HLS,DASH,MSS,CMAF&quot;\n      DistributionId: !Ref CloudFront\n      EnableMediaPackage: !Ref EnableMediaPackage\n</code></pre>\n<p>Thus, you can inspect the lambda function, and try to debug it. It will be available in your Lambda console.</p>\n<p>Also the error you are getting is <a href=\"https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_Errors\" rel=\"nofollow noreferrer\">500</a>, which means this is lambda service error itself. Could be some temporary issue on the AWS side:</p>\n<blockquote>\n<p>ServiceException -The <strong>AWS Lambda service encountered an internal error</strong>.\nHTTP Status Code: 500</p>\n</blockquote>\n<p>Based on the comments and chat discussion:</p>\n<p>A <strong>recommended</strong> solution was to check in <strong>different region</strong>. And in did, the <strong>template works</strong> in <code>us-west-2</code>.</p>\n<p>The list of supported regions for <code>AWS Elemental MediaPackage</code> can be found <a href=\"https://docs.amazonaws.cn/en_us/general/latest/gr/mediapackage.html#mediapackage_region\" rel=\"nofollow noreferrer\">here</a>.</p>\n", "OwnerUserId": "248823", "LastEditorUserId": "248823", "LastEditDate": "2020-08-05T08:09:56.010", "LastActivityDate": "2020-08-05T08:09:56.010", "CommentCount": "10", "ContentLicense": "CC BY-SA 4.0", "comments": [{"Id": "111862685", "PostId": "63256674", "Score": "0", "Text": "I used us-east-1 region and didn't make any change in template. 5 days before it's working correctly but suddenly start giving this 500 error. After that i'm getting the same error. I delete everything and try to start from beginning but same issue with MediaPackageVod. Only 500 error i'm getting.", "CreationDate": "2020-08-05T06:47:08.460", "UserId": "11850616", "filtered-sentences": [{"source": "Text", "text": "I used us-east-1 region and didn't make any change in template. ", "keywords": ["change"]}]}, {"Id": "111862762", "PostId": "63256674", "Score": "0", "Text": "If i share my aws credential with you, can you be able to help?", "CreationDate": "2020-08-05T06:50:08.733", "UserId": "11850616", "filtered-sentences": []}, {"Id": "111862768", "PostId": "63256674", "Score": "1", "Text": "@AbdullahKhan Hi. 500 is an internal lambda service issue. Such issues should be fixed by AWS, not a customer. I tested it on `us-east-1`. It worked, but I did it only once. Maybe was lucky? You can try different region, but I'm not sure what changes to the template would need to be done to work in other regions.", "CreationDate": "2020-08-05T06:50:27.773", "UserId": "248823", "filtered-sentences": [{"source": "Text", "text": "I tested it on `us-east-1`. ", "keywords": ["test"]}, {"source": "Text", "text": "You can try different region, but I'm not sure what changes to the template would need to be done to work in other regions.", "keywords": ["change"]}]}, {"Id": "111862881", "PostId": "63256674", "Score": "0", "Text": "I try to contact them before but it's appear \"Technical support is unavailable under basic support plan\". Is there any other way to contact them for help?", "CreationDate": "2020-08-05T06:54:59.663", "UserId": "11850616", "filtered-sentences": []}, {"Id": "111862989", "PostId": "63256674", "Score": "1", "Text": "@AbdullahKhan I see. Don't know. The cheapest support plan is [Developer plan](https://aws.amazon.com/premiumsupport/plans/developers/), but obviously it is not free. But have you checked your `Personal Health Dashboard` (search in console for this service). Maybe it has some notifications about issues related to lambda?", "CreationDate": "2020-08-05T06:58:56.493", "UserId": "248823", "filtered-sentences": [{"source": "Text", "text": "The cheapest support plan is [Developer plan](https://aws.amazon.com/premiumsupport/plans/developers/), but obviously it is not free. ", "keywords": ["cheap"]}]}, {"Id": "111863853", "PostId": "63256674", "Score": "0", "Text": "Last issue there is closed on 29 july 2020.\nWe have identified the cause of the increased API error rates in a single Availability Zone in the US-EAST-1 Region and continue working towards resolution. Customers experiencing errors launching new EC2 instances may attempt to launch their EC2 instances in another Availability Zone. Existing running instances are unaffected.", "CreationDate": "2020-08-05T07:34:36.503", "UserId": "11850616", "filtered-sentences": []}, {"Id": "111863920", "PostId": "63256674", "Score": "1", "Text": "@AbdullahKhan This is only for EC2, does not seem to be related to lambda. And also its not today nor yesterday. Don't know. You can way and check other day, or different region. Don't have any more ideas what to recommend. Sorry :-(", "CreationDate": "2020-08-05T07:36:57.407", "UserId": "248823", "filtered-sentences": []}, {"Id": "111864012", "PostId": "63256674", "Score": "0", "Text": "One last question, can we get \"internal server error\" when we don't  have permissions to create some of the resources?", "CreationDate": "2020-08-05T07:40:27.787", "UserId": "11850616", "filtered-sentences": [{"source": "Text", "text": "One last question, can we get \"internal server error\" when we don't have permissions to create some of the resources?", "keywords": ["permissions"]}]}, {"Id": "111864051", "PostId": "63256674", "Score": "0", "Text": "Let us [continue this discussion in chat](https://chat.stackoverflow.com/rooms/219243/discussion-between-marcin-and-abdullah-khan).", "CreationDate": "2020-08-05T07:42:21.903", "UserId": "248823", "filtered-sentences": []}, {"Id": "126063567", "PostId": "63256674", "Score": "0", "Text": "hi @Marcin, I am also working on the template, I want to have meaningful names for objects in the destination s3 bucket, for that requirement where should I make a change in the template file? \nand what is the meaning of \"!Ref\" in the following lines:\n\" StackName: !Ref AWS::StackName \"", "CreationDate": "2022-03-02T07:55:47.167", "UserId": "16516624", "filtered-sentences": [{"source": "Text", "text": "hi @Marcin, I am also working on the template, I want to have meaningful names for objects in the destination s3 bucket, for that requirement where should I make a change in the template file? and what is the meaning of \"!Ref\" in the following lines: \" StackName: !Ref AWS::StackName \"", "keywords": ["change"]}]}], "history": [{"Id": "228136459", "PostHistoryTypeId": "5", "PostId": "63256674", "RevisionGUID": "20527c88-b939-47be-b2b4-76915e73ca19", "CreationDate": "2020-08-05T08:09:56.010", "UserId": "248823", "Comment": "added 169 characters in body", "Text": "The **template works**. I deployed it myself on my sandbox account. Thus, I can't replicate the issue and the fault must be somewhere else.\r\n\r\n[![enter image description here][1]][1]\r\n\r\nI used `us-east-1` region with all values of the template set to their default. Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources?\r\n\r\nIf this helps, in your case the lambda function associated with the  following custom resource fails:\r\n\r\n```\r\n  MediaPackageVod:\r\n    Type: Custom::LoadLambda\r\n    Properties:\r\n      ServiceToken: !GetAtt CustomResource.Arn\r\n      Resource: MediaPackageVod\r\n      StackName: !Ref AWS::StackName\r\n      GroupId: !Sub \"${AWS::StackName}-packaging-group\"\r\n      PackagingConfigurations: \"HLS,DASH,MSS,CMAF\"\r\n      DistributionId: !Ref CloudFront\r\n      EnableMediaPackage: !Ref EnableMediaPackage\r\n```\r\n\r\nThus, you can inspect the lambda function, and try to debug it. It will be available in your Lambda console.\r\n\r\nAlso the error you are getting is [500][2], which means this is lambda service error itself. Could be some temporary issue on the AWS side:\r\n\r\n>  ServiceException -The **AWS Lambda service encountered an internal error**.\r\n    HTTP Status Code: 500\r\n\r\n\r\nBased on the comments and chat discussion: \r\n\r\nA **recommended** solution was to check in **different region**. And in did, the **template works** in `us-west-2`.\r\n\r\nThe list of supported regions for `AWS Elemental MediaPackage` can be found [here](https://docs.amazonaws.cn/en_us/general/latest/gr/mediapackage.html#mediapackage_region).\r\n\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/2Q7w5.png\r\n  [2]: https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_Errors", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources? ", "keywords": ["change", "permissions"]}]}, {"Id": "228118364", "PostHistoryTypeId": "2", "PostId": "63256674", "RevisionGUID": "dbdccb32-0f72-473e-8c6f-1f10ddf56f38", "CreationDate": "2020-08-05T00:10:33.897", "UserId": "248823", "Text": "The **template works**. I deployed it myself on my sandbox account. Thus, I can't replicate the issue and the fault must be somewhere else.\r\n\r\n[![enter image description here][1]][1]\r\n\r\nI used `us-east-1` region with all values of the template set to their default. Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources?\r\n\r\nIf this helps, in your case the lambda function associated with the  following custom resource fails:\r\n\r\n```\r\n  MediaPackageVod:\r\n    Type: Custom::LoadLambda\r\n    Properties:\r\n      ServiceToken: !GetAtt CustomResource.Arn\r\n      Resource: MediaPackageVod\r\n      StackName: !Ref AWS::StackName\r\n      GroupId: !Sub \"${AWS::StackName}-packaging-group\"\r\n      PackagingConfigurations: \"HLS,DASH,MSS,CMAF\"\r\n      DistributionId: !Ref CloudFront\r\n      EnableMediaPackage: !Ref EnableMediaPackage\r\n```\r\n\r\nThus, you can inspect the lambda function, and try to debug it. It will be available in your Lambda console.\r\n\r\n  [1]: https://i.stack.imgur.com/2Q7w5.png", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources? ", "keywords": ["change", "permissions"]}]}, {"Id": "228118497", "PostHistoryTypeId": "5", "PostId": "63256674", "RevisionGUID": "1a95555d-00e0-443e-8cb0-d7632e330a7e", "CreationDate": "2020-08-05T00:15:50.633", "UserId": "248823", "Comment": "added 341 characters in body", "Text": "The **template works**. I deployed it myself on my sandbox account. Thus, I can't replicate the issue and the fault must be somewhere else.\r\n\r\n[![enter image description here][1]][1]\r\n\r\nI used `us-east-1` region with all values of the template set to their default. Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources?\r\n\r\nIf this helps, in your case the lambda function associated with the  following custom resource fails:\r\n\r\n```\r\n  MediaPackageVod:\r\n    Type: Custom::LoadLambda\r\n    Properties:\r\n      ServiceToken: !GetAtt CustomResource.Arn\r\n      Resource: MediaPackageVod\r\n      StackName: !Ref AWS::StackName\r\n      GroupId: !Sub \"${AWS::StackName}-packaging-group\"\r\n      PackagingConfigurations: \"HLS,DASH,MSS,CMAF\"\r\n      DistributionId: !Ref CloudFront\r\n      EnableMediaPackage: !Ref EnableMediaPackage\r\n```\r\n\r\nThus, you can inspect the lambda function, and try to debug it. It will be available in your Lambda console.\r\n\r\nAlso the error you are getting is [500][2], which means this is lambda service error itself. Could be some temporary issue on the AWS side:\r\n\r\n>  ServiceException -The **AWS Lambda service encountered an internal error**.\r\n    HTTP Status Code: 500\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/2Q7w5.png\r\n  [2]: https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_Errors", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources? ", "keywords": ["change", "permissions"]}]}], "filtered-sentences": [{"source": "Body", "text": "Maybe you've changed the default settings to some incorrect ones, or you have no permissions to create some of the resources? ", "keywords": ["change", "permissions"]}]}], "contains-topic": true, "filtered-sentences": []}